#!/bin/sh
#
# This script is the entrypoint for the storetheindex docker container
set -e
user=storetheindex
repo="$STORETHEINDEX_PATH"

if [ `id -u` -eq 0 ]; then
  echo "Changing user to $user"
  # ensure folder is writable
  su-exec "$user" test -w "$repo" || chown -R -- "$user" "$repo"
  # restart script with new privileges
  exec su-exec "$user" "$0" "$@"
fi

# 2nd invocation with regular user

if [ -e "$repo/config" ]; then
  echo "Found storetheindex repo at $repo"
else
  storetheindex init
fi

exec storetheindex "$@"
