// Code adapted from original generated by github.com/whyrusleeping/cbor-gen.
// This adapted code allows for an optional OrigPeer field.
//
// TODO: Convert Message into IPLD schema and use bindnode for serialization.

package message

import (
	"fmt"
	"io"

	cbg "github.com/whyrusleeping/cbor-gen"
)

func (m *Message) MarshalCBOR(w io.Writer) error {
	var err error

	if m == nil {
		_, err = w.Write(cbg.CborNull)
		return err
	}

	var lengthBufMessage []byte
	if m.OrigPeer == "" {
		lengthBufMessage = []byte{131}
	} else {
		lengthBufMessage = []byte{132}
	}
	if _, err = w.Write(lengthBufMessage); err != nil {
		return err
	}

	scratch := make([]byte, 9)

	// Encode m.Cid.
	if err = cbg.WriteCidBuf(scratch, w, m.Cid); err != nil {
		return fmt.Errorf("failed to write cid field m.Cid: %w", err)
	}

	// Encode m.Addrs.
	if len(m.Addrs) > cbg.MaxLength {
		return fmt.Errorf("slice value in field m.Addrs was too long")
	}

	if err = cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajArray, uint64(len(m.Addrs))); err != nil {
		return err
	}
	for _, v := range m.Addrs {
		if len(v) > cbg.ByteArrayMaxLen {
			return fmt.Errorf("byte array in field v was too long")
		}

		if err = cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajByteString, uint64(len(v))); err != nil {
			return err
		}

		if _, err = w.Write(v[:]); err != nil {
			return err
		}
	}

	if len(m.ExtraData) > cbg.ByteArrayMaxLen {
		return fmt.Errorf("byte array in field m.ExtraData was too long")
	}

	if err = cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajByteString, uint64(len(m.ExtraData))); err != nil {
		return err
	}

	if _, err = w.Write(m.ExtraData[:]); err != nil {
		return err
	}

	// OrigPeer is empty so do not encode it.
	if len(m.OrigPeer) == 0 {
		return nil
	}

	// Encode m.OrigPeer.
	if len(m.OrigPeer) > cbg.MaxLength {
		return fmt.Errorf("value in field m.OrigPeer was too long")
	}

	if err = cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajTextString, uint64(len(m.OrigPeer))); err != nil {
		return err
	}
	if _, err = io.WriteString(w, string(m.OrigPeer)); err != nil {
		return err
	}

	return nil
}

func (m *Message) UnmarshalCBOR(r io.Reader) error {
	*m = Message{}

	br := cbg.GetPeeker(r)
	scratch := make([]byte, 8)

	maj, extra, err := cbg.CborReadHeaderBuf(br, scratch)
	if err != nil {
		return err
	}
	if maj != cbg.MajArray {
		return fmt.Errorf("cbor input should be of type array")
	}

	if extra > 4 {
		return fmt.Errorf("cbor input had too many fields")
	}
	if extra < 3 {
		return fmt.Errorf("cbor input had too few fields")
	}
	var hasOrigPeer bool
	if extra == 4 {
		hasOrigPeer = true
	}

	// Decode m.Cid.
	m.Cid, err = cbg.ReadCid(br)
	if err != nil {
		return fmt.Errorf("failed to read cid field m.Cid: %w", err)
	}

	// Decode m.Addrs.
	maj, extra, err = cbg.CborReadHeaderBuf(br, scratch)
	if err != nil {
		return err
	}

	if extra > cbg.MaxLength {
		return fmt.Errorf("m.Addrs: array too large (%d)", extra)
	}

	if maj != cbg.MajArray {
		return fmt.Errorf("expected cbor array")
	}

	if extra > 0 {
		m.Addrs = make([][]uint8, extra)
	}

	for i := 0; i < int(extra); i++ {
		maj, extra, err := cbg.CborReadHeaderBuf(br, scratch)
		if err != nil {
			return err
		}

		if extra > cbg.ByteArrayMaxLen {
			return fmt.Errorf("byte array too large (%d) for Addrs[%d]", extra, i)
		}
		if maj != cbg.MajByteString {
			return fmt.Errorf("expected byte array")
		}

		if extra > 0 {
			m.Addrs[i] = make([]uint8, extra)
		}

		if _, err = io.ReadFull(br, m.Addrs[i][:]); err != nil {
			return err
		}
	}

	// Decode m.ExtraData.
	maj, extra, err = cbg.CborReadHeaderBuf(br, scratch)
	if err != nil {
		return err
	}

	if extra > cbg.ByteArrayMaxLen {
		return fmt.Errorf("byte array too large (%d) for ExtraData", extra)
	}
	if maj != cbg.MajByteString {
		return fmt.Errorf("expected byte array")
	}

	if extra > 0 {
		m.ExtraData = make([]uint8, extra)
	}

	if _, err = io.ReadFull(br, m.ExtraData[:]); err != nil {
		return err
	}

	// OrigPeer field does not exist, so nothing more to do.
	if !hasOrigPeer {
		return nil
	}

	// Decode m.OrigPeer.
	sval, err := cbg.ReadString(br)
	if err != nil {
		return err
	}
	m.OrigPeer = string(sval)

	return nil
}
